### ISSUE TITLE
I've seen gamepad support in RetroPie

### ISSUE THREAD

**Issue by BondarenkoArtur** [tsoding/grub-gamepad#2]
But unfortunately I was not able to find how exactly it was implemented... Sorry...
maybe something from here will be helpful
https://github.com/RetroPie/RetroPie-Setup/wiki/Controller-configuration-(driver-level)

**Comment by rexim** [comment]
@BondarenkoArtur thanks! I'll take a look!

**Comment by rexim** [comment]
from https://retropie.org.uk/

> RetroPie sits on top of a full OS, 

Too high-level for us
